# Generated by Django 4.2.3 on 2023-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('j', 'jeans'), ('t_s', 'T-Shirt'), ('sw', 'Sweater'), ('hi_sw', 'Hi-Winter Sweater'), ('s', 'Shirt'), ('l_u_s', 'Ladies Uni Sweater')], max_length=5)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
