# Generated by Django 4.2.3 on 2023-08-12 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('J', 'jeans'), ('T_S', 'T-Shirt'), ('SW', 'Sweater'), ('Hi_W_SW', 'Hi-Winter Sweater'), ('S', 'Shirt'), ('L_U_S', 'Ladies Uni Sweater')], max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='Product'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Udham Singh nagar', 'Udham Singh nagar'), ('Greater Noida', 'Greater Noida'), ('Uttarakhan', 'Uttarakhan'), ('Punjab', 'Punjab'), ('Tripura', 'Tripura'), ('Hariyana', 'Hariyana'), ('Udisa', 'Udisa'), ('Telangana', 'Telangana'), ('Bihar', 'Bihar'), ('West Bengal', 'West Bengal'), ('Goa', 'Goa'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujrat'), ('Sikkim', 'Sikkim'), ('Noida', 'Noida'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('jaspur Udham Singh nagar', 'jaspur Udham Singh nagar'), ('Karnatak', 'Karnatak'), ('Tamil Nadu', 'Tamil Nadu'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajisthan', 'Rajisthan')], max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
