# Generated by Django 4.2.3 on 2023-09-02 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_customer_state_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('West Bengal', 'West Bengal'), ('Assam', 'Assam'), ('Sikkim', 'Sikkim'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Greater Noida', 'Greater Noida'), ('Tripura', 'Tripura'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Delhi', 'Delhi'), ('jaspur Udham Singh nagar', 'jaspur Udham Singh nagar'), ('Gujrat', 'Gujrat'), ('Udham Singh nagar', 'Udham Singh nagar'), ('Tamil Nadu', 'Tamil Nadu'), ('Hariyana', 'Hariyana'), ('Mumbai', 'Mumbai'), ('Bihar', 'Bihar'), ('Udisa', 'Udisa'), ('Uttarakhan', 'Uttarakhan'), ('Noida', 'Noida'), ('Rajisthan', 'Rajisthan'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Karnatak', 'Karnatak'), ('Telangana', 'Telangana'), ('Goa', 'Goa'), ('Punjab', 'Punjab'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
