# Generated by Django 4.2.3 on 2023-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_customer_orderplaced_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Karnatak', 'Karnatak'), ('Hariyana', 'Hariyana'), ('Udham Singh nagar', 'Udham Singh nagar'), ('Punjab', 'Punjab'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Sikkim', 'Sikkim'), ('Greater Noida', 'Greater Noida'), ('Assam', 'Assam'), ('Telangana', 'Telangana'), ('Noida', 'Noida'), ('Mumbai', 'Mumbai'), ('Tripura', 'Tripura'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Delhi', 'Delhi'), ('West Bengal', 'West Bengal'), ('Rajisthan', 'Rajisthan'), ('Gujrat', 'Gujrat'), ('Uttarakhan', 'Uttarakhan'), ('Madhya Pradesh', 'Madhya Pradesh'), ('jaspur Udham Singh nagar', 'jaspur Udham Singh nagar'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Udisa', 'Udisa')], max_length=100),
        ),
    ]
