# Generated by Django 5.0.2 on 2024-02-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Karnatak', 'Karnatak'), ('Greater Noida', 'Greater Noida'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhan', 'Uttarakhan'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujrat', 'Gujrat'), ('Mumbai', 'Mumbai'), ('Bihar', 'Bihar'), ('Rajisthan', 'Rajisthan'), ('Delhi', 'Delhi'), ('Noida', 'Noida'), ('Punjab', 'Punjab'), ('Udisa', 'Udisa'), ('Hariyana', 'Hariyana'), ('Udham Singh nagar', 'Udham Singh nagar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Sikkim', 'Sikkim'), ('jaspur Udham Singh nagar', 'jaspur Udham Singh nagar'), ('Assam', 'Assam'), ('Tripura', 'Tripura'), ('Madhya Pradesh', 'Madhya Pradesh'), ('West Bengal', 'West Bengal'), ('Goa', 'Goa')], max_length=100),
        ),
    ]
